// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcELOLokmnlSv8_I2AnKyqpiAiCYf4Duk',
    appId: '1:1014376255744:android:d2e9b89666af9ba975e3e5',
    messagingSenderId: '1014376255744',
    projectId: 'avdan-918fc',
    storageBucket: 'avdan-918fc.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZKMVhPc5LreUhisyWQBWJURIeDS_h5c',
    appId: '1:1014376255744:web:1e88fba3cc9a661875e3e5',
    messagingSenderId: '1014376255744',
    projectId: 'avdan-918fc',
    authDomain: 'avdan-918fc.firebaseapp.com',
    storageBucket: 'avdan-918fc.appspot.com',
    measurementId: 'G-S56TGQ2EE6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QhGDsTF5htM4NZrzFO79hu4A2DXxUrE',
    appId: '1:1014376255744:ios:a8d2e683a4b5fce675e3e5',
    messagingSenderId: '1014376255744',
    projectId: 'avdan-918fc',
    storageBucket: 'avdan-918fc.appspot.com',
    iosBundleId: 'com.alkaitagi.avdan',
  );

}